// Presentation metadata only. Defaults and value choices come from Config.zig.
const Key = @import("key.zig").Key;
pub const Entry = struct { key: Key, group: u8, zh: []const u8, en: []const u8, example: ?[]const u8 = null, note: ?[]const u8 = null };
pub const entries = [_]Entry{
    .{ .key = .command, .group = 1, .zh = "新终端启动命令／Shell", .en = "Terminal shell or command", .example = "/bin/zsh", .note = "留空使用系统登录 Shell；命令路径必须可执行。 / Unset uses the login shell; the command must be executable." },
    .{ .key = .@"initial-command", .group = 1, .zh = "初次启动专用命令", .en = "Command for the first terminal", .example = "/bin/zsh", .note = "留空沿用 command。 / Unset inherits command." },
    .{ .key = .@"working-directory", .group = 1, .zh = "初始工作目录", .en = "Working directory", .example = "home", .note = "留空自动选择；home 为用户主目录，或填写有效绝对路径。 / Automatic when unset; use home or an existing absolute path." },
    .{ .key = .env, .group = 1, .zh = "进程环境变量", .en = "Process environment variables", .example = "MY_VARIABLE=hello", .note = "变量名=值；可重复。不建议在配置中保存密钥。 / NAME=value; repeatable. Avoid storing secrets here." },
    .{ .key = .input, .group = 1, .zh = "进程启动时的预设输入", .en = "Input sent to a new process", .example = "string:echo hello\\n", .note = "string: 后的转义文本会发送到新进程；也支持 path: 文件。 / Escaped text after string: is sent to the new process; path: reads a file." },
    .{ .key = .@"wait-after-command", .group = 1, .zh = "命令退出后等待关闭", .en = "Keep terminal open after the command exits" },
    .{ .key = .@"abnormal-command-exit-runtime", .group = 1, .zh = "异常快速退出判定时间", .en = "Short command exit threshold", .note = "单位：毫秒。 / Milliseconds." },
    .{ .key = .@"window-inherit-working-directory", .group = 1, .zh = "新窗口继承工作目录", .en = "New windows inherit the working directory" },
    .{ .key = .@"tab-inherit-working-directory", .group = 1, .zh = "新标签继承工作目录", .en = "New tabs inherit the working directory" },
    .{ .key = .@"split-inherit-working-directory", .group = 1, .zh = "新分屏继承工作目录", .en = "New splits inherit the working directory" },
    .{ .key = .@"confirm-close-surface", .group = 1, .zh = "关闭终端时确认策略", .en = "Terminal close confirmation" },
    .{ .key = .@"quit-after-last-window-closed", .group = 1, .zh = "关闭最后窗口时退出应用", .en = "Quit after the last window closes" },
    .{ .key = .@"initial-window", .group = 1, .zh = "启动时创建初始窗口", .en = "Create a window on launch" },
    .{ .key = .@"undo-timeout", .group = 1, .zh = "关闭会话可撤销的保留时长", .en = "Retention time for undoing a closed terminal", .example = "10s" },
    .{ .key = .@"shell-integration", .group = 1, .zh = "Shell 集成检测／注入", .en = "Shell integration detection and injection" },
    .{ .key = .@"shell-integration-features", .group = 1, .zh = "Shell 集成功能集合", .en = "Shell integration features" },
    .{ .key = .@"macos-hidden", .group = 1, .zh = "应用启动时隐藏策略", .en = "Application visibility on launch" },
    .{ .key = .@"macos-dock-drop-behavior", .group = 1, .zh = "文件拖到 Dock 图标后的行为", .en = "Action for files dropped onto the Dock icon" },
    .{ .key = .@"font-family", .group = 2, .zh = "字体与后备字体", .en = "Font family", .example = "Menlo", .note = "可重复添加后备字体；先写空值可清除原列表。留空使用内置 Sarasa Term SC Nerd（Unhinted Regular），粗体和斜体遵循合成样式设置。 / Repeat for fallback fonts; an empty entry clears the list. Unset uses bundled Sarasa Term SC Nerd (Unhinted Regular); bold/italic follow synthetic style settings." },
    .{ .key = .@"font-family-bold", .group = 2, .zh = "粗体字体", .en = "Font family bold", .example = "Menlo" },
    .{ .key = .@"font-family-italic", .group = 2, .zh = "斜体字体", .en = "Font family italic", .example = "Menlo" },
    .{ .key = .@"font-family-bold-italic", .group = 2, .zh = "粗斜体字体", .en = "Font family bold italic", .example = "Menlo" },
    .{ .key = .@"font-style", .group = 2, .zh = "常规字体样式", .en = "Font style", .example = "Regular", .note = "样式名必须由所选字体提供；通常保留 default。 / The selected font must provide the named style; normally leave this at default." },
    .{ .key = .@"font-style-bold", .group = 2, .zh = "粗体样式", .en = "Font style bold" },
    .{ .key = .@"font-style-italic", .group = 2, .zh = "斜体样式", .en = "Font style italic" },
    .{ .key = .@"font-style-bold-italic", .group = 2, .zh = "粗斜体样式", .en = "Font style bold italic" },
    .{ .key = .@"font-synthetic-style", .group = 2, .zh = "允许合成的字体样式", .en = "Font synthetic style" },
    .{ .key = .@"font-feature", .group = 2, .zh = "OpenType 字体特性／连字", .en = "OpenType font features and ligatures", .example = "-liga", .note = "OpenType 特性；如 -liga 关闭连字。可重复。 / OpenType feature; -liga disables ligatures. Repeatable." },
    .{ .key = .@"font-size", .group = 2, .zh = "字号", .en = "Font size", .example = "14", .note = "单位：点；必须大于零。 / Points; must be positive." },
    .{ .key = .@"font-variation", .group = 2, .zh = "常规可变字体轴", .en = "Variable font axes", .example = "wght=400", .note = "轴名=值；需字体支持该可变轴，可重复。 / Axis=value; requires a variable font supporting that axis. Repeatable." },
    .{ .key = .@"font-variation-bold", .group = 2, .zh = "粗体可变字体轴", .en = "Font variation bold", .example = "wght=400", .note = "轴名=值；需字体支持该可变轴，可重复。 / Axis=value; requires a variable font supporting that axis. Repeatable." },
    .{ .key = .@"font-variation-italic", .group = 2, .zh = "斜体可变字体轴", .en = "Font variation italic", .example = "wght=400", .note = "轴名=值；需字体支持该可变轴，可重复。 / Axis=value; requires a variable font supporting that axis. Repeatable." },
    .{ .key = .@"font-variation-bold-italic", .group = 2, .zh = "粗斜体可变字体轴", .en = "Font variation bold italic", .example = "wght=400", .note = "轴名=值；需字体支持该可变轴，可重复。 / Axis=value; requires a variable font supporting that axis. Repeatable." },
    .{ .key = .@"font-thicken", .group = 2, .zh = "字体加厚", .en = "Font thicken" },
    .{ .key = .@"font-thicken-strength", .group = 2, .zh = "加厚强度", .en = "Font thicken strength", .note = "0～255；仅在 font-thicken 开启时有效。 / 0–255; requires font-thicken." },
    .{ .key = .@"font-shaping-break", .group = 2, .zh = "字形塑形断开规则", .en = "Font shaping break rules" },
    .{ .key = .@"alpha-blending", .group = 2, .zh = "文字与背景颜色混合方式", .en = "Alpha blending" },
    .{ .key = .@"adjust-cell-width", .group = 2, .zh = "字符单元宽度微调", .en = "Adjust cell width", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-cell-height", .group = 2, .zh = "字符单元高度微调", .en = "Adjust cell height", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-font-baseline", .group = 2, .zh = "文字基线微调", .en = "Adjust font baseline", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-underline-position", .group = 2, .zh = "下划线位置", .en = "Adjust underline position", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-underline-thickness", .group = 2, .zh = "下划线粗细", .en = "Adjust underline thickness", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-strikethrough-position", .group = 2, .zh = "删除线位置", .en = "Adjust strikethrough position", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-strikethrough-thickness", .group = 2, .zh = "删除线粗细", .en = "Adjust strikethrough thickness", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-overline-position", .group = 2, .zh = "上划线位置", .en = "Adjust overline position", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-overline-thickness", .group = 2, .zh = "上划线粗细", .en = "Adjust overline thickness", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-cursor-thickness", .group = 2, .zh = "光标粗细微调", .en = "Adjust cursor thickness", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-cursor-height", .group = 2, .zh = "光标高度微调", .en = "Adjust cursor height", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-box-thickness", .group = 2, .zh = "框线字符粗细", .en = "Adjust box thickness", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .@"adjust-icon-height", .group = 2, .zh = "图标字符高度", .en = "Adjust icon height", .example = "1", .note = "像素增减量或百分比，例如 1 或 10%。 / Pixel adjustment or percentage, such as 1 or 10%." },
    .{ .key = .theme, .group = 2, .zh = "主题；支持明暗主题组合", .en = "Theme", .example = "light:3024 Day,dark:3024 Night" },
    .{ .key = .background, .group = 2, .zh = "终端背景色", .en = "Background" },
    .{ .key = .foreground, .group = 2, .zh = "终端文字色", .en = "Foreground" },
    .{ .key = .@"background-image", .group = 2, .zh = "背景图片", .en = "Background image", .example = "?/absolute/path/background.png", .note = "替换成实际图片路径；? 表示可选资源。 / Replace with an image path; ? marks an optional resource." },
    .{ .key = .@"background-image-opacity", .group = 2, .zh = "背景图片不透明度", .en = "Background image opacity", .note = "范围：0～1。 / Range: 0–1." },
    .{ .key = .@"background-image-position", .group = 2, .zh = "背景图片位置", .en = "Background image position" },
    .{ .key = .@"background-image-fit", .group = 2, .zh = "背景图片缩放方式", .en = "Background image fit" },
    .{ .key = .@"background-image-repeat", .group = 2, .zh = "背景图片平铺", .en = "Background image repeat" },
    .{ .key = .@"minimum-contrast", .group = 2, .zh = "最低对比度", .en = "Minimum contrast", .note = "对比度比值：1～21；1 不额外增强。 / Contrast ratio 1–21; 1 leaves contrast unchanged." },
    .{ .key = .palette, .group = 2, .zh = "终端 256 色调色板覆盖", .en = "Palette", .example = "1=#bf616a", .note = "索引 0～255；可重复设置不同索引。 / Index 0–255; repeat for multiple colors." },
    .{ .key = .@"palette-generate", .group = 2, .zh = "自动生成扩展调色板", .en = "Palette generate" },
    .{ .key = .@"palette-harmonious", .group = 2, .zh = "扩展调色板协调处理", .en = "Palette harmonious" },
    .{ .key = .@"background-opacity", .group = 2, .zh = "背景不透明度", .en = "Background opacity", .example = "0.9", .note = "范围：0～1。 / Range: 0–1." },
    .{ .key = .@"background-opacity-cells", .group = 2, .zh = "显式背景色单元应用不透明度", .en = "Background opacity cells" },
    .{ .key = .@"background-blur", .group = 2, .zh = "背景模糊", .en = "Background blur", .note = "false 关闭，true 使用默认强度，整数指定强度。 / false disables, true uses default strength, an integer sets the strength." },
    .{ .key = .@"bold-color", .group = 2, .zh = "粗体文字颜色策略", .en = "Bold color", .example = "bright" },
    .{ .key = .@"faint-opacity", .group = 2, .zh = "弱化文字不透明度", .en = "Faint opacity", .note = "范围：0～1。 / Range: 0–1." },
    .{ .key = .@"cursor-color", .group = 2, .zh = "光标颜色", .en = "Cursor color", .example = "#d8dee9" },
    .{ .key = .@"cursor-opacity", .group = 2, .zh = "光标不透明度", .en = "Cursor opacity", .note = "范围：0～1。 / Range: 0–1." },
    .{ .key = .@"cursor-style", .group = 2, .zh = "光标形状", .en = "Cursor style" },
    .{ .key = .@"cursor-style-blink", .group = 2, .zh = "光标闪烁策略", .en = "Cursor style blink", .example = "true", .note = "留空允许程序控制闪烁。 / Unset allows terminal applications to control blinking." },
    .{ .key = .@"cursor-text", .group = 2, .zh = "光标覆盖处的文字色", .en = "Cursor text", .example = "#282c34" },
    .{ .key = .@"cursor-effect", .group = 2, .zh = "光标动画：开启／关闭", .en = "Cursor effect" },
    .{ .key = .@"selection-foreground", .group = 2, .zh = "选中文字色", .en = "Selection foreground", .example = "#ffffff" },
    .{ .key = .@"selection-background", .group = 2, .zh = "选区背景色", .en = "Selection background", .example = "#3b4252" },
    .{ .key = .@"search-foreground", .group = 2, .zh = "普通搜索结果文字色", .en = "Search foreground" },
    .{ .key = .@"search-background", .group = 2, .zh = "普通搜索结果背景色", .en = "Search background" },
    .{ .key = .@"search-selected-foreground", .group = 2, .zh = "当前搜索结果文字色", .en = "Search selected foreground" },
    .{ .key = .@"search-selected-background", .group = 2, .zh = "当前搜索结果背景色", .en = "Search selected background" },
    .{ .key = .maximize, .group = 3, .zh = "新窗口最大化", .en = "Maximize new windows" },
    .{ .key = .fullscreen, .group = 3, .zh = "新窗口全屏策略", .en = "New window fullscreen mode" },
    .{ .key = .title, .group = 3, .zh = "固定终端标题", .en = "Fixed terminal title", .example = "My Terminal" },
    .{ .key = .@"window-padding-x", .group = 3, .zh = "水平内边距", .en = "Window padding x" },
    .{ .key = .@"window-padding-y", .group = 3, .zh = "垂直内边距", .en = "Window padding y" },
    .{ .key = .@"window-padding-balance", .group = 3, .zh = "内边距平衡", .en = "Window padding balance" },
    .{ .key = .@"window-padding-color", .group = 3, .zh = "内边距颜色策略", .en = "Window padding color" },
    .{ .key = .@"window-inherit-font-size", .group = 3, .zh = "新窗口／标签继承字号", .en = "Window inherit font size" },
    .{ .key = .@"window-decoration", .group = 3, .zh = "窗口装饰", .en = "Window decoration" },
    .{ .key = .@"window-title-font-family", .group = 3, .zh = "窗口与标签标题字体", .en = "Window title font family", .example = "Helvetica Neue" },
    .{ .key = .@"window-theme", .group = 3, .zh = "窗口明暗外观", .en = "Window theme" },
    .{ .key = .@"window-colorspace", .group = 3, .zh = "窗口色彩空间", .en = "Window colorspace" },
    .{ .key = .@"window-height", .group = 3, .zh = "初始窗口行数", .en = "Window height", .example = "30", .note = "字符行数；0 自动决定。 / Character rows; 0 means automatic." },
    .{ .key = .@"window-width", .group = 3, .zh = "初始窗口列数", .en = "Window width", .example = "100", .note = "字符列数；0 自动决定。 / Character columns; 0 means automatic." },
    .{ .key = .@"window-position-x", .group = 3, .zh = "初始水平位置", .en = "Window position x", .example = "50", .note = "相对可用屏幕左上角，单位：点；与 y 一起设置。 / Points from the usable screen top-left; set together with y." },
    .{ .key = .@"window-position-y", .group = 3, .zh = "初始垂直位置", .en = "Window position y", .example = "50", .note = "相对可用屏幕左上角，单位：点；与 x 一起设置。 / Points from the usable screen top-left; set together with x." },
    .{ .key = .@"window-save-state", .group = 3, .zh = "窗口状态恢复策略", .en = "Window save state" },
    .{ .key = .@"window-step-resize", .group = 3, .zh = "按字符尺寸步进缩放", .en = "Window step resize" },
    .{ .key = .@"window-new-tab-position", .group = 3, .zh = "新标签插入位置", .en = "Window new tab position" },
    .{ .key = .@"macos-non-native-fullscreen", .group = 3, .zh = "非原生全屏模式", .en = "macOS non native fullscreen" },
    .{ .key = .@"macos-window-buttons", .group = 3, .zh = "窗口红黄绿按钮", .en = "macOS window buttons" },
    .{ .key = .@"macos-titlebar-style", .group = 3, .zh = "标题栏样式", .en = "macOS titlebar style" },
    .{ .key = .@"macos-titlebar-proxy-icon", .group = 3, .zh = "标题栏目录代理图标", .en = "macOS titlebar proxy icon" },
    .{ .key = .@"macos-window-shadow", .group = 3, .zh = "窗口阴影", .en = "macOS window shadow" },
    .{ .key = .@"unfocused-split-opacity", .group = 3, .zh = "未聚焦分屏不透明度", .en = "Unfocused split opacity", .note = "范围：0～1。 / Range: 0–1." },
    .{ .key = .@"unfocused-split-fill", .group = 3, .zh = "未聚焦分屏填充色", .en = "Unfocused split fill", .example = "#282c34" },
    .{ .key = .@"split-divider-color", .group = 3, .zh = "分隔线颜色", .en = "Split divider color", .example = "#4c566a" },
    .{ .key = .@"split-preserve-zoom", .group = 3, .zh = "执行分屏操作时保留放大状态", .en = "Split preserve zoom" },
    .{ .key = .@"drag-handle", .group = 3, .zh = "分屏拖动手柄显示策略", .en = "Drag handle" },
    .{ .key = .@"resize-overlay", .group = 3, .zh = "缩放时显示行列数的策略", .en = "Resize overlay" },
    .{ .key = .@"resize-overlay-position", .group = 3, .zh = "缩放提示位置", .en = "Resize overlay position" },
    .{ .key = .@"resize-overlay-duration", .group = 3, .zh = "缩放提示持续时间", .en = "Resize overlay duration", .example = "750ms" },
    .{ .key = .@"quick-terminal-position", .group = 4, .zh = "出现位置", .en = "Quick terminal position", .note = "需设置 toggle_quick_terminal 快捷键才能呼出。 / Bind toggle_quick_terminal to show the quick terminal." },
    .{ .key = .@"quick-terminal-size", .group = 4, .zh = "快捷终端尺寸", .en = "Quick terminal size", .example = "50%,100%", .note = "默认按位置和显示器计算；尺寸必须带 % 或 px，可用逗号分隔主轴、次轴。 / Defaults depend on position and screen; use % or px, optionally primary,secondary." },
    .{ .key = .@"quick-terminal-screen", .group = 4, .zh = "目标显示器", .en = "Quick terminal screen" },
    .{ .key = .@"quick-terminal-animation-duration", .group = 4, .zh = "显示／隐藏动画时长", .en = "Quick terminal animation duration", .note = "单位：秒；0 关闭动画。 / Seconds; 0 disables animation." },
    .{ .key = .@"quick-terminal-autohide", .group = 4, .zh = "失去焦点时自动隐藏", .en = "Quick terminal autohide" },
    .{ .key = .@"quick-terminal-space-behavior", .group = 4, .zh = "跨桌面空间行为", .en = "Quick terminal space behavior" },
    .{ .key = .@"cursor-click-to-move", .group = 5, .zh = "点击移动命令行光标", .en = "Click to move the shell cursor" },
    .{ .key = .keybind, .group = 5, .zh = "快捷键、组合键序列、键表及全局快捷键", .en = "Keyboard shortcuts, sequences and tables", .example = "super+shift+t=new_tab", .note = "可重复；同一触发键的新绑定覆盖旧绑定。全局快捷键使用 global: 前缀。 / Repeatable; later bindings replace the same trigger. Use global: for global shortcuts." },
    .{ .key = .@"key-remap", .group = 5, .zh = "修饰键重映射", .en = "Modifier key remapping", .example = "ctrl=super" },
    .{ .key = .@"macos-option-as-alt", .group = 5, .zh = "Option 键作为 Alt 的策略", .en = "macOS option as alt", .example = "left", .note = "留空按键盘布局自动决定；left 仅使用左 Option。 / Unset follows keyboard layout; left uses only left Option." },
    .{ .key = .@"mouse-hide-while-typing", .group = 5, .zh = "输入时隐藏鼠标", .en = "Mouse hide while typing" },
    .{ .key = .@"mouse-shift-capture", .group = 5, .zh = "Shift 与终端鼠标捕获策略", .en = "Mouse shift capture" },
    .{ .key = .@"mouse-reporting", .group = 5, .zh = "允许终端程序接收鼠标事件", .en = "Mouse reporting" },
    .{ .key = .@"mouse-scroll-multiplier", .group = 5, .zh = "触控板／滚轮滚动倍数", .en = "Mouse scroll multiplier" },
    .{ .key = .@"right-click-action", .group = 5, .zh = "右键动作", .en = "Right click action" },
    .{ .key = .@"middle-click-action", .group = 5, .zh = "中键动作", .en = "Middle click action" },
    .{ .key = .@"click-repeat-interval", .group = 5, .zh = "连续点击判定间隔", .en = "Click repeat interval", .note = "单位：毫秒；0 使用系统设置。 / Milliseconds; 0 uses system settings." },
    .{ .key = .@"focus-follows-mouse", .group = 5, .zh = "焦点跟随鼠标", .en = "Focus follows mouse" },
    .{ .key = .@"selection-clear-on-typing", .group = 5, .zh = "输入时清除选区", .en = "Selection clear on typing" },
    .{ .key = .@"selection-clear-on-copy", .group = 5, .zh = "复制后清除选区", .en = "Selection clear on copy" },
    .{ .key = .@"selection-word-chars", .group = 5, .zh = "双击选词字符规则", .en = "Selection word chars" },
    .{ .key = .@"clipboard-codepoint-map", .group = 5, .zh = "复制时字符映射", .en = "Character replacements when copying", .example = "U+2500=U+002D", .note = "Unicode 字符或范围=替代字符或文字；可重复。 / Unicode character/range=replacement character/text; repeatable." },
    .{ .key = .@"clipboard-trim-trailing-spaces", .group = 5, .zh = "复制时移除行尾空格", .en = "Clipboard trim trailing spaces" },
    .{ .key = .@"copy-on-select", .group = 5, .zh = "选中即复制的策略", .en = "Copy selected text automatically" },
    .{ .key = .@"scroll-to-bottom", .group = 6, .zh = "自动回到底部的触发条件", .en = "Events that scroll to the bottom" },
    .{ .key = .@"scrollback-limit-bytes", .group = 6, .zh = "滚动历史字节上限", .en = "Scrollback limit bytes", .note = "单位：字节；也接受 unlimited。 / Bytes; also accepts unlimited." },
    .{ .key = .@"scrollback-limit-lines", .group = 6, .zh = "滚动历史行数上限", .en = "Scrollback limit lines", .note = "单位：行；也接受 unlimited。 / Lines; also accepts unlimited." },
    .{ .key = .@"scrollback-compression", .group = 6, .zh = "滚动历史压缩", .en = "Scrollback compression" },
    .{ .key = .scrollbar, .group = 6, .zh = "滚动条显示策略", .en = "Scrollbar visibility" },
    .{ .key = .@"link-url", .group = 6, .zh = "自动识别 URL", .en = "Link URL" },
    .{ .key = .@"link-osc8", .group = 6, .zh = "允许终端程序声明 OSC 8 链接", .en = "Link OSC 8" },
    .{ .key = .@"link-previews", .group = 6, .zh = "链接地址预览", .en = "Link address previews" },
    .{ .key = .@"clipboard-read", .group = 7, .zh = "终端程序读取剪贴板的策略", .en = "Clipboard read" },
    .{ .key = .@"clipboard-write", .group = 7, .zh = "终端程序写入剪贴板的策略", .en = "Clipboard write" },
    .{ .key = .@"clipboard-write-limit-bytes", .group = 7, .zh = "写入剪贴板大小限制", .en = "Clipboard write limit bytes", .note = "单位：字节；也接受 unlimited。 / Bytes; also accepts unlimited." },
    .{ .key = .@"clipboard-paste-protection", .group = 7, .zh = "粘贴保护", .en = "Clipboard paste protection" },
    .{ .key = .@"clipboard-paste-bracketed-safe", .group = 7, .zh = "括号粘贴视为安全的策略", .en = "Clipboard paste bracketed safe" },
    .{ .key = .@"notify-on-command-finish", .group = 7, .zh = "命令完成时何时通知", .en = "Notify on command finish" },
    .{ .key = .@"notify-on-command-finish-action", .group = 7, .zh = "命令完成通知动作", .en = "Notify on command finish action" },
    .{ .key = .@"notify-on-command-finish-after", .group = 7, .zh = "通知所需最短命令运行时间", .en = "Notify on command finish after", .example = "5s" },
    .{ .key = .@"bell-features", .group = 7, .zh = "终端铃声引发的提示动作", .en = "Bell features" },
    .{ .key = .@"bell-audio-path", .group = 7, .zh = "铃声音频文件", .en = "Bell audio path", .example = "?/absolute/path/bell.aiff", .note = "替换成实际音频路径；? 表示可选资源。 / Replace with an audio path; ? marks an optional resource." },
    .{ .key = .@"bell-audio-volume", .group = 7, .zh = "铃声音量", .en = "Bell audio volume", .note = "范围：0～1。 / Range: 0–1." },
    .{ .key = .@"desktop-notifications", .group = 7, .zh = "允许终端桌面通知", .en = "Desktop notifications" },
    .{ .key = .@"progress-style", .group = 7, .zh = "系统进度提示", .en = "System progress indicator" },
    .{ .key = .@"macos-auto-secure-input", .group = 7, .zh = "密码输入时自动开启安全输入", .en = "Enable Secure Input for password prompts" },
    .{ .key = .@"macos-secure-input-indication", .group = 7, .zh = "安全输入状态提示", .en = "Show Secure Input status" },
    .{ .key = .@"macos-applescript", .group = 7, .zh = "允许 AppleScript 控制", .en = "Allow AppleScript control" },
    .{ .key = .@"macos-shortcuts", .group = 7, .zh = "快捷指令控制应用的许可策略", .en = "Shortcuts app control permissions" },
    .{ .key = .@"title-report", .group = 7, .zh = "允许程序读取窗口标题", .en = "Allow programs to query window titles" },
    .{ .key = .@"vt-kam-allowed", .group = 7, .zh = "允许终端键盘锁定模式", .en = "Allow terminal keyboard locking" },
    .{ .key = .@"font-codepoint-map", .group = 8, .zh = "按字符范围指定字体", .en = "Fonts for Unicode character ranges", .example = "U+E000-U+F8FF=Menlo", .note = "Unicode 范围=字体；可重复。字体应已安装。 / Unicode range=font; repeatable. The font should be installed." },
    .{ .key = .@"grapheme-width-method", .group = 8, .zh = "Unicode 字素宽度计算策略", .en = "Grapheme width method" },
    .{ .key = .@"config-file", .group = 8, .zh = "包含其他配置文件", .en = "Additional configuration files", .example = "?extra.ghostty", .note = "相对路径以本文件目录为基准；? 允许文件不存在。引用文件后加载，可覆盖主配置和启动参数。 / Relative to this file; ? allows a missing file. Included files load last and can override main-file and CLI values." },
    .{ .key = .@"command-palette-entry", .group = 8, .zh = "自定义命令面板条目", .en = "Command palette entry", .example = "title:New Tab,action:new_tab", .note = "可重复添加；clear 清空，空值恢复内置条目。 / Repeat to add; clear removes all entries, an empty value restores built-ins." },
    .{ .key = .@"window-vsync", .group = 8, .zh = "垂直同步", .en = "Vertical synchronization" },
    .{ .key = .@"image-storage-limit", .group = 8, .zh = "终端图像存储上限", .en = "Terminal image storage limit", .note = "单位：字节。 / Bytes." },
    .{ .key = .@"osc-color-report-format", .group = 8, .zh = "OSC 颜色查询响应格式", .en = "Color query response format" },
    .{ .key = .term, .group = 8, .zh = "TERM 环境标识", .en = "TERM environment identifier" },
    .{ .key = .@"enquiry-response", .group = 8, .zh = "ENQ 查询响应文本", .en = "Response text for ENQ queries", .example = "cghostty" },
};
