// Generated by zig build update-config-bridge. Do not edit.
import GhosttyKit

extension Ghostty {
    /// Typed borrowed reads, used only while copying a native snapshot.
    nonisolated enum ConfigSchema {
        struct Key<Value>: Sendable {
            fileprivate let name: String

            fileprivate init(_ name: String) { self.name = name }

            @MainActor
            func read(from config: ghostty_config_t, into value: inout Value) -> Bool {
                withUnsafeMutablePointer(to: &value) { pointer in
                    ghostty_config_get(config, pointer, name, UInt(name.utf8.count))
                }
            }
        }

        static let abnormalCommandExitRuntime = Key<CUnsignedInt>("abnormal-command-exit-runtime")
        static let background = Key<ghostty_config_color_s>("background")
        static let backgroundBlur = Key<Int16>("background-blur")
        static let backgroundOpacity = Key<Double>("background-opacity")
        static let bellAudioPath = Key<ghostty_config_path_s>("bell-audio-path")
        static let bellAudioVolume = Key<Double>("bell-audio-volume")
        static let bellFeatures = Key<CUnsignedInt>("bell-features")
        static let commandPaletteEntry = Key<ghostty_config_command_list_s>("command-palette-entry")
        static let dragHandle = Key<UnsafePointer<CChar>?>("drag-handle")
        static let focusFollowsMouse = Key<Bool>("focus-follows-mouse")
        static let fullscreen = Key<UnsafePointer<CChar>?>("fullscreen")
        static let initialWindow = Key<Bool>("initial-window")
        static let macosApplescript = Key<Bool>("macos-applescript")
        static let macosAutoSecureInput = Key<Bool>("macos-auto-secure-input")
        static let macosDockDropBehavior = Key<UnsafePointer<CChar>?>("macos-dock-drop-behavior")
        static let macosHidden = Key<UnsafePointer<CChar>?>("macos-hidden")
        static let macosNonNativeFullscreen = Key<UnsafePointer<CChar>?>("macos-non-native-fullscreen")
        static let macosSecureInputIndication = Key<Bool>("macos-secure-input-indication")
        static let macosShortcuts = Key<UnsafePointer<CChar>?>("macos-shortcuts")
        static let macosTitlebarProxyIcon = Key<UnsafePointer<CChar>?>("macos-titlebar-proxy-icon")
        static let macosTitlebarStyle = Key<UnsafePointer<CChar>?>("macos-titlebar-style")
        static let macosWindowButtons = Key<UnsafePointer<CChar>?>("macos-window-buttons")
        static let macosWindowShadow = Key<Bool>("macos-window-shadow")
        static let maximize = Key<Bool>("maximize")
        static let notifyOnCommandFinish = Key<UnsafePointer<CChar>?>("notify-on-command-finish")
        static let notifyOnCommandFinishAction = Key<CUnsignedInt>("notify-on-command-finish-action")
        static let notifyOnCommandFinishAfter = Key<UInt>("notify-on-command-finish-after")
        static let progressStyle = Key<Bool>("progress-style")
        static let quickTerminalAnimationDuration = Key<Double>("quick-terminal-animation-duration")
        static let quickTerminalAutohide = Key<Bool>("quick-terminal-autohide")
        static let quickTerminalPosition = Key<UnsafePointer<CChar>?>("quick-terminal-position")
        static let quickTerminalScreen = Key<UnsafePointer<CChar>?>("quick-terminal-screen")
        static let quickTerminalSize = Key<ghostty_config_quick_terminal_size_s>("quick-terminal-size")
        static let quickTerminalSpaceBehavior = Key<UnsafePointer<CChar>?>("quick-terminal-space-behavior")
        static let quitAfterLastWindowClosed = Key<Bool>("quit-after-last-window-closed")
        static let resizeOverlay = Key<UnsafePointer<CChar>?>("resize-overlay")
        static let resizeOverlayDuration = Key<UInt>("resize-overlay-duration")
        static let resizeOverlayPosition = Key<UnsafePointer<CChar>?>("resize-overlay-position")
        static let scrollbar = Key<UnsafePointer<CChar>?>("scrollbar")
        static let splitDividerColor = Key<ghostty_config_color_s>("split-divider-color")
        static let splitPreserveZoom = Key<CUnsignedInt>("split-preserve-zoom")
        static let title = Key<UnsafePointer<CChar>?>("title")
        static let undoTimeout = Key<UInt>("undo-timeout")
        static let unfocusedSplitFill = Key<ghostty_config_color_s>("unfocused-split-fill")
        static let unfocusedSplitOpacity = Key<Double>("unfocused-split-opacity")
        static let windowDecoration = Key<UnsafePointer<CChar>?>("window-decoration")
        static let windowNewTabPosition = Key<UnsafePointer<CChar>?>("window-new-tab-position")
        static let windowPositionX = Key<Int16>("window-position-x")
        static let windowPositionY = Key<Int16>("window-position-y")
        static let windowSaveState = Key<UnsafePointer<CChar>?>("window-save-state")
        static let windowStepResize = Key<Bool>("window-step-resize")
        static let windowTheme = Key<UnsafePointer<CChar>?>("window-theme")
        static let windowTitleFontFamily = Key<UnsafePointer<CChar>?>("window-title-font-family")
    }
}
